"""Per-table CLIF 2.1.0 pandera schemas + registry (U3).

The ``<table>.py`` modules are generated by ``scripts/gen_schemas.py`` from the
vendored data dictionary; ``base.py`` holds the shared column factories. Use
``get_schema(table)`` to resolve a table name to its committed ``SCHEMA``.
"""

from __future__ import annotations

import importlib

import pandera.polars as pa

from clifforge.reference import loader
from clifforge.schemas import base

__all__ = ["base", "get_schema", "has_schema", "schema_tables"]


def schema_tables() -> list[str]:
    """Every table with a generated schema module (== the dictionary tables)."""
    return loader.dictionary_tables()


def has_schema(table: str) -> bool:
    return table in set(schema_tables())


def get_schema(table: str) -> pa.DataFrameSchema:
    """Return the committed ``SCHEMA`` for ``table`` (raises ``KeyError`` if unknown)."""
    if not has_schema(table):
        raise KeyError(f"No schema for table {table!r}. Known: {', '.join(schema_tables())}")
    module = importlib.import_module(f"clifforge.schemas.{table}")
    schema: pa.DataFrameSchema = module.SCHEMA
    return schema
