"""AUTO-GENERATED by scripts/gen_schemas.py from the CLIF 2.1.0 data dictionary.

Do not hand-edit the generated column list; regenerate with
``uv run python scripts/gen_schemas.py``. A table unit MAY append clinical-coupling
refinements below SCHEMA via .update_column()/.add_columns() (see U3 / R15).

Table: adt (beta)
"""

from __future__ import annotations

import pandera.polars as pa

from clifforge.schemas import base

SCHEMA: pa.DataFrameSchema = pa.DataFrameSchema(
    {
        "hospitalization_id": base.id_column(),
        "hospital_id": base.id_column(),
        "hospital_type": base.category("adt", "hospital_type_category"),
        "in_dttm": base.utc_datetime(),
        "out_dttm": base.utc_datetime(),
        "location_name": base.string(),
        "location_category": base.category("adt", "location_category"),
        "location_type": base.category("adt", "location_type"),
    },
    strict=False,
    coerce=False,
    name="adt",
)
