"""AUTO-GENERATED by scripts/gen_schemas.py from the CLIF 2.1.0 data dictionary.

Do not hand-edit the generated column list; regenerate with
``uv run python scripts/gen_schemas.py``. A table unit MAY append clinical-coupling
refinements below SCHEMA via .update_column()/.add_columns() (see U3 / R15).

Table: key_icu_orders (concept)
"""

from __future__ import annotations

import pandera.polars as pa

from clifforge.schemas import base

SCHEMA: pa.DataFrameSchema = pa.DataFrameSchema(
    {
        "hospitalization_id": base.id_column(),
        "order_dttm": base.utc_datetime(),
        "order_name": base.string(),
        "order_category": base.category("key_icu_orders", "order_category"),
        "order_status_name": base.string(),
    },
    strict=False,
    coerce=False,
    name="key_icu_orders",
)
