"""AUTO-GENERATED by scripts/gen_schemas.py from the CLIF 2.1.0 data dictionary.

Do not hand-edit the generated column list; regenerate with
``uv run python scripts/gen_schemas.py``. A table unit MAY append clinical-coupling
refinements below SCHEMA via .update_column()/.add_columns() (see U3 / R15).

Table: labs (beta)
"""

from __future__ import annotations

import pandera.polars as pa

from clifforge.schemas import base

SCHEMA: pa.DataFrameSchema = pa.DataFrameSchema(
    {
        "hospitalization_id": base.id_column(),
        "lab_order_dttm": base.utc_datetime(),
        "lab_collect_dttm": base.utc_datetime(),
        "lab_result_dttm": base.utc_datetime(),
        "lab_order_name": base.string(),
        "lab_order_category": base.category("labs", "lab_order_category"),
        "lab_name": base.string(),
        "lab_category": base.category("labs", "lab_category"),
        "lab_value": base.string(),
        "lab_value_numeric": base.plain_float(),
        "reference_unit": base.string(),
        "lab_specimen_name": base.string(),
        "lab_specimen_category": base.string(),
        "lab_loinc_code": base.string(),
    },
    strict=False,
    coerce=False,
    name="labs",
)
