"""AUTO-GENERATED by scripts/gen_schemas.py from the CLIF 2.1.0 data dictionary.

Do not hand-edit the generated column list; regenerate with
``uv run python scripts/gen_schemas.py``. A table unit MAY append clinical-coupling
refinements below SCHEMA via .update_column()/.add_columns() (see U3 / R15).

Table: medication_orders (concept)
"""

from __future__ import annotations

import pandera.polars as pa

from clifforge.schemas import base

SCHEMA: pa.DataFrameSchema = pa.DataFrameSchema(
    {
        "hospitalization_id": base.id_column(),
        "med_order_id": base.id_column(),
        "order_start_dttm": base.utc_datetime(),
        "order_end_dttm": base.utc_datetime(),
        "ordered_dttm": base.utc_datetime(),
        "med_name": base.string(),
        "med_category": base.string(),
        "med_group": base.string(),
        "med_order_status_name": base.string(),
        "med_order_status_category": base.string(),
        "med_route_name": base.string(),
        "med_dose": base.plain_float(),
        "med_dose_unit": base.string(),
        "med_frequency": base.string(),
        "prn": base.boolean(),
    },
    strict=False,
    coerce=False,
    name="medication_orders",
)
