"""AUTO-GENERATED by scripts/gen_schemas.py from the CLIF 2.1.0 data dictionary.

Do not hand-edit the generated column list; regenerate with
``uv run python scripts/gen_schemas.py``. A table unit MAY append clinical-coupling
refinements below SCHEMA via .update_column()/.add_columns() (see U3 / R15).

Table: microbiology_nonculture (beta)
"""

from __future__ import annotations

import pandera.polars as pa

from clifforge.schemas import base

SCHEMA: pa.DataFrameSchema = pa.DataFrameSchema(
    {
        "hospitalization_id": base.id_column(),
        "result_dttm": base.string(),
        "collect_dttm": base.string(),
        "order_dttm": base.string(),
        "fluid_name": base.string(),
        "component_category": base.string(),
        "result_unit_category": base.string(),
        "result_category": base.category("microbiology_nonculture", "result_category"),
    },
    strict=False,
    coerce=False,
    name="microbiology_nonculture",
)
