"""AUTO-GENERATED by scripts/gen_schemas.py from the CLIF 2.1.0 data dictionary.

Do not hand-edit the generated column list; regenerate with
``uv run python scripts/gen_schemas.py``. A table unit MAY append clinical-coupling
refinements below SCHEMA via .update_column()/.add_columns() (see U3 / R15).

Table: patient_assessments (beta)
"""

from __future__ import annotations

import pandera.polars as pa

from clifforge.schemas import base

SCHEMA: pa.DataFrameSchema = pa.DataFrameSchema(
    {
        "hospitalization_id": base.id_column(),
        "recorded_dttm": base.utc_datetime(),
        "assessment_name": base.string(),
        "assessment_category": base.category("patient_assessments", "assessment_category"),
        "assessment_group": base.string(),
        "numerical_value": base.plain_float(),
        "categorical_value": base.string(),
        "text_value": base.string(),
    },
    strict=False,
    coerce=False,
    name="patient_assessments",
)
