"""AUTO-GENERATED by scripts/gen_schemas.py from the CLIF 2.1.0 data dictionary.

Do not hand-edit the generated column list; regenerate with
``uv run python scripts/gen_schemas.py``. A table unit MAY append clinical-coupling
refinements below SCHEMA via .update_column()/.add_columns() (see U3 / R15).

Table: provider (concept)
"""

from __future__ import annotations

import pandera.polars as pa

from clifforge.schemas import base

SCHEMA: pa.DataFrameSchema = pa.DataFrameSchema(
    {
        "hospitalization_id": base.id_column(),
        "provider_id": base.id_column(),
        "start_dttm": base.utc_datetime(),
        "stop_dttm": base.utc_datetime(),
        "provider_role_name": base.string(),
        "provider_role_category": base.string(),
    },
    strict=False,
    coerce=False,
    name="provider",
)
