"""AUTO-GENERATED by scripts/gen_schemas.py from the CLIF 2.1.0 data dictionary.

Do not hand-edit the generated column list; regenerate with
``uv run python scripts/gen_schemas.py``. A table unit MAY append clinical-coupling
refinements below SCHEMA via .update_column()/.add_columns() (see U3 / R15).

Table: respiratory_support (beta)
"""

from __future__ import annotations

import pandera.polars as pa

from clifforge.schemas import base

SCHEMA: pa.DataFrameSchema = pa.DataFrameSchema(
    {
        "hospitalization_id": base.id_column(),
        "recorded_dttm": base.utc_datetime(),
        "device_name": base.string(),
        "device_id": base.id_column(),
        "device_category": base.category("respiratory_support", "device_category"),
        "vent_brand_name": base.string(),
        "mode_name": base.string(),
        "mode_category": base.category("respiratory_support", "mode_category"),
        "tracheostomy": base.integer(),
        "fio2_set": base.bounded_float("respiratory_support", "fio2_set"),
        "lpm_set": base.bounded_float("respiratory_support", "lpm_set"),
        "tidal_volume_set": base.bounded_float("respiratory_support", "tidal_volume_set"),
        "resp_rate_set": base.bounded_float("respiratory_support", "resp_rate_set"),
        "pressure_control_set": base.bounded_float("respiratory_support", "pressure_control_set"),
        "pressure_support_set": base.bounded_float("respiratory_support", "pressure_support_set"),
        "flow_rate_set": base.bounded_float("respiratory_support", "flow_rate_set"),
        "peak_inspiratory_pressure_set": base.bounded_float(
            "respiratory_support", "peak_inspiratory_pressure_set"
        ),
        "inspiratory_time_set": base.bounded_float("respiratory_support", "inspiratory_time_set"),
        "peep_set": base.bounded_float("respiratory_support", "peep_set"),
        "tidal_volume_obs": base.bounded_float("respiratory_support", "tidal_volume_obs"),
        "resp_rate_obs": base.bounded_float("respiratory_support", "resp_rate_obs"),
        "plateau_pressure_obs": base.bounded_float("respiratory_support", "plateau_pressure_obs"),
        "peak_inspiratory_pressure_obs": base.bounded_float(
            "respiratory_support", "peak_inspiratory_pressure_obs"
        ),
        "peep_obs": base.bounded_float("respiratory_support", "peep_obs"),
        "minute_vent_obs": base.bounded_float("respiratory_support", "minute_vent_obs"),
        "mean_airway_pressure_obs": base.bounded_float(
            "respiratory_support", "mean_airway_pressure_obs"
        ),
    },
    strict=False,
    coerce=False,
    name="respiratory_support",
)
