"""AUTO-GENERATED by scripts/gen_schemas.py from the CLIF 2.1.0 data dictionary.

Do not hand-edit the generated column list; regenerate with
``uv run python scripts/gen_schemas.py``. A table unit MAY append clinical-coupling
refinements below SCHEMA via .update_column()/.add_columns() (see U3 / R15).

Table: transfusion (concept)
"""

from __future__ import annotations

import pandera.polars as pa

from clifforge.schemas import base

SCHEMA: pa.DataFrameSchema = pa.DataFrameSchema(
    {
        "hospitalization_id": base.id_column(),
        "transfusion_start_dttm": base.utc_datetime(),
        "transfusion_end_dttm": base.utc_datetime(),
        "component_name": base.string(),
        "attribute_name": base.string(),
        "volume_transfused": base.plain_float(),
        "volume_units": base.string(),
        "product_code": base.string(),
    },
    strict=False,
    coerce=False,
    name="transfusion",
)
